spring:
  application:
    name: apollo-configservice
  profiles:
    active: noauth
  http:
    converters:
      preferred-json-mapper: gson
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/ApolloConfigDB?useUnicode=true&characterEncoding=gbk&autoReconnect=true&autoReconnectForPools=true&noAccessToProcedureBodies=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: apollo
    password: apollo
server:
  port: 8080