spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  resources:
    cache-period: 3600
server:
  port: 8070
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP