spring:
  application:
    name: apollo-portal
  profiles:
    active: auth
  http:
    converters:
      preferred-json-mapper: gson
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/ApolloPortalDB?useUnicode=true&characterEncoding=gbk&autoReconnect=true&autoReconnectForPools=true&noAccessToProcedureBodies=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: apollo
    password: apollo
  resources:
    cache-period: 3600
server:
  port: 8070
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP